# Generated by Django 4.2.2 on 2023-06-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(help_text='Title of the blog (e.g Success of Hardworker)', max_length=200, verbose_name='Post')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name (e.g Usman)', max_length=20, verbose_name='F-Name')),
                ('last_name', models.CharField(help_text='Enter your last name (e.g Ashir)', max_length=20, verbose_name='L-Name')),
                ('nationality', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Niger', 'Niger'), ('Saudi Arabia', 'Saudi Arabia'), ('Sudan', 'Sudan'), ('USA', 'United State of America'), ('UK', 'United Kingdom'), ('Others', 'Others')], default='Nigeria', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Write Your Date of Birth (e.g 14/03/2001)')),
                ('biograpy', models.TextField(help_text='Write a short history about your life', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Write your comment here!', max_length=200)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.blogger'),
        ),
    ]
