# Generated by Django 4.2.2 on 2023-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blogger_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='nationality',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('Niger', 'Niger'), ('Saudi Arabia', 'Saudi Arabia'), ('Sudan', 'Sudan'), ('USA', 'United State of America'), ('UK', 'United Kingdom'), ('Others', 'Others')], default='Nigeria', max_length=20),
        ),
    ]
