# Generated by Django 4.2.2 on 2023-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(help_text='Write your comment here!', max_length=200),
        ),
    ]
