# Generated by Django 4.2.2 on 2023-07-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date'], 'permissions': (('can_add_post', 'create new post'),)},
        ),
    ]
