# Generated by Django 4.2.2 on 2023-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Title of the blog (e.g Success of Hardworker)', max_length=50, verbose_name='Title'),
        ),
    ]
