# Generated by Django 4.2.2 on 2023-07-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_blog_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date'], 'permissions': (('can_edit_post', 'Edit post'),)},
        ),
    ]
