# Generated by Django 4.2.2 on 2023-07-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date'], 'permissions': (('can_edit_blog', 'Edit blog'), ('can_add_blog', 'Add blog'))},
        ),
    ]
